### ISSUE TITLE
merging with clams-python repo

### ISSUE THREAD

**Issue by keighrim** [clamsproject/app-nlp-example#1]
It seems that we could benefit from merging this repo as a part of documentation for `clams-python`. I'd like to hear how others think.

**Comment by marcverhagen** [comment]
We would definitely benefit by somehow integrating this repository. Merging with `clams-python` does not sound quite right to me because this is as much an example for `mmif-python` as it is for `clams-python`. We do have the documentation section on clams.ai, which could be a good candidate for storing this stuff. Or, and this would be the least work, we can refer to this repository (and others like it) from the documentation section on clams.ai and any other repo that feels like it, including `clams-python`.

**Comment by keighrim** [comment]
Superceded by #8 and https://github.com/clamsproject/clams-python/issues/161.
